services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ureg-laravel-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ureg-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ureg_exchange_rates
      MYSQL_USER: ureg
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: node:20
    container_name: ureg-react
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

volumes:
  db-data:
